    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.SendMedia") Pyrogram 2.3.45 thinks: The button url is invalid
01:14:01 AM - 47 - root - __init__ - ERROR - ❌ Ping Failed: Cannot connect to host 0.0.0.0:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
All filenames notification have been deleted.
01:18:59 AM - 47 - root - __init__ - ERROR - ❌ Ping Failed: Cannot connect to host 0.0.0.0:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
Error In Verification - Telegram says: [400 BUTTON_URL_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The button url is invalid
